<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.4.12 setup script
 * Date: Wed, 16 Sep 2015 08:17:17 +0200
 */

/* Servers configuration */
$i = 0;

/* Server: bsquared [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'bsquared';
$cfg['Servers'][$i]['host'] = 'us-cdbr-azure-west-c.cloudapp.net';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['pmadb'] = 'acsm_426fce9e8c80a33';
$cfg['Servers'][$i]['bookmarktable'] = 'pma__bookmark';
$cfg['Servers'][$i]['relation'] = 'pma__relation';
$cfg['Servers'][$i]['userconfig'] = 'pma__userconfig';
$cfg['Servers'][$i]['users'] = 'pma__users';
$cfg['Servers'][$i]['usergroups'] = 'pma__usergroups';
$cfg['Servers'][$i]['navigationhiding'] = 'pma__navigationhiding';
$cfg['Servers'][$i]['table_info'] = 'pma__table_info';
$cfg['Servers'][$i]['column_info'] = 'pma__column_info';
$cfg['Servers'][$i]['history'] = 'pma__history';
$cfg['Servers'][$i]['recent'] = 'pma__recent';
$cfg['Servers'][$i]['favorite'] = 'pma__favorite';
$cfg['Servers'][$i]['table_uiprefs'] = 'pma__table_uiprefs';
$cfg['Servers'][$i]['tracking'] = 'pma__tracking';
$cfg['Servers'][$i]['table_coords'] = 'pma__table_coords';
$cfg['Servers'][$i]['pdf_pages'] = 'pma__pdf_pages';
$cfg['Servers'][$i]['savedsearches'] = 'pma__savedsearches';
$cfg['Servers'][$i]['central_columns'] = 'pma__central_columns';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['controlhost'] = 'us-cdbr-azure-west-c.cloudapp.net';
$cfg['Servers'][$i]['controluser'] = 'bea1032a957a19';
$cfg['Servers'][$i]['controlpass'] = 'c03cc102';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'q^fZBqV4mWAAg}W}@U%v*{Q_7n2jOmmaAm[%SNJj';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>